// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: raftkv/v1/raftkv.proto

package raftkvv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType mirrors the Raft core's message types.
//
// The zero value is UNSPECIFIED rather than a real type. Proto3 cannot
// distinguish an unset field from one explicitly set to zero, so making zero
// meaningful would let a malformed or truncated message silently decode as a
// valid vote request.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED               MessageType = 0
	MessageType_MESSAGE_TYPE_VOTE_REQUEST              MessageType = 1
	MessageType_MESSAGE_TYPE_VOTE_RESPONSE             MessageType = 2
	MessageType_MESSAGE_TYPE_APPEND_REQUEST            MessageType = 3
	MessageType_MESSAGE_TYPE_APPEND_RESPONSE           MessageType = 4
	MessageType_MESSAGE_TYPE_HEARTBEAT                 MessageType = 5
	MessageType_MESSAGE_TYPE_HEARTBEAT_RESPONSE        MessageType = 6
	MessageType_MESSAGE_TYPE_INSTALL_SNAPSHOT          MessageType = 7
	MessageType_MESSAGE_TYPE_INSTALL_SNAPSHOT_RESPONSE MessageType = 8
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_VOTE_REQUEST",
		2: "MESSAGE_TYPE_VOTE_RESPONSE",
		3: "MESSAGE_TYPE_APPEND_REQUEST",
		4: "MESSAGE_TYPE_APPEND_RESPONSE",
		5: "MESSAGE_TYPE_HEARTBEAT",
		6: "MESSAGE_TYPE_HEARTBEAT_RESPONSE",
		7: "MESSAGE_TYPE_INSTALL_SNAPSHOT",
		8: "MESSAGE_TYPE_INSTALL_SNAPSHOT_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":               0,
		"MESSAGE_TYPE_VOTE_REQUEST":              1,
		"MESSAGE_TYPE_VOTE_RESPONSE":             2,
		"MESSAGE_TYPE_APPEND_REQUEST":            3,
		"MESSAGE_TYPE_APPEND_RESPONSE":           4,
		"MESSAGE_TYPE_HEARTBEAT":                 5,
		"MESSAGE_TYPE_HEARTBEAT_RESPONSE":        6,
		"MESSAGE_TYPE_INSTALL_SNAPSHOT":          7,
		"MESSAGE_TYPE_INSTALL_SNAPSHOT_RESPONSE": 8,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_raftkv_v1_raftkv_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_raftkv_v1_raftkv_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{0}
}

// EntryType mirrors the Raft core's entry types.
type EntryType int32

const (
	EntryType_ENTRY_TYPE_UNSPECIFIED EntryType = 0
	EntryType_ENTRY_TYPE_NORMAL      EntryType = 1
	EntryType_ENTRY_TYPE_NO_OP       EntryType = 2
	EntryType_ENTRY_TYPE_CONF_CHANGE EntryType = 3
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "ENTRY_TYPE_NORMAL",
		2: "ENTRY_TYPE_NO_OP",
		3: "ENTRY_TYPE_CONF_CHANGE",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED": 0,
		"ENTRY_TYPE_NORMAL":      1,
		"ENTRY_TYPE_NO_OP":       2,
		"ENTRY_TYPE_CONF_CHANGE": 3,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_raftkv_v1_raftkv_proto_enumTypes[1].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_raftkv_v1_raftkv_proto_enumTypes[1]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{1}
}

// NodeState mirrors the Raft core's roles.
type NodeState int32

const (
	NodeState_NODE_STATE_UNSPECIFIED NodeState = 0
	NodeState_NODE_STATE_FOLLOWER    NodeState = 1
	NodeState_NODE_STATE_CANDIDATE   NodeState = 2
	NodeState_NODE_STATE_LEADER      NodeState = 3
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "NODE_STATE_UNSPECIFIED",
		1: "NODE_STATE_FOLLOWER",
		2: "NODE_STATE_CANDIDATE",
		3: "NODE_STATE_LEADER",
	}
	NodeState_value = map[string]int32{
		"NODE_STATE_UNSPECIFIED": 0,
		"NODE_STATE_FOLLOWER":    1,
		"NODE_STATE_CANDIDATE":   2,
		"NODE_STATE_LEADER":      3,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_raftkv_v1_raftkv_proto_enumTypes[2].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_raftkv_v1_raftkv_proto_enumTypes[2]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{2}
}

// Entry is one record in the replicated log. The pair (term, index) identifies
// it uniquely across the cluster.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Term  uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Type  EntryType              `protobuf:"varint,3,opt,name=type,proto3,enum=raftkv.v1.EntryType" json:"type,omitempty"`
	// Opaque to the consensus layer; only the state machine interprets it.
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Entry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Message is one Raft message. It mirrors the core's single flat envelope, so
// the transport has exactly one shape to encode and the chaos harness one
// shape to delay, drop, and reorder.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=raftkv.v1.MessageType" json:"type,omitempty"`
	From  uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To    uint64                 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Term  uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	// Candidate log position, for a vote request.
	LastLogIndex uint64 `protobuf:"varint,5,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm  uint64 `protobuf:"varint,6,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	// The entry immediately preceding entries, for an append.
	PrevLogIndex uint64   `protobuf:"varint,7,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm  uint64   `protobuf:"varint,8,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries      []*Entry `protobuf:"bytes,9,rep,name=entries,proto3" json:"entries,omitempty"`
	CommitIndex  uint64   `protobuf:"varint,10,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	Granted      bool     `protobuf:"varint,11,opt,name=granted,proto3" json:"granted,omitempty"`
	Success      bool     `protobuf:"varint,12,opt,name=success,proto3" json:"success,omitempty"`
	MatchIndex   uint64   `protobuf:"varint,13,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	// Backup hint from a rejected append, letting the leader skip a whole term
	// rather than one index per round trip.
	ConflictIndex uint64 `protobuf:"varint,14,opt,name=conflict_index,json=conflictIndex,proto3" json:"conflict_index,omitempty"`
	ConflictTerm  uint64 `protobuf:"varint,15,opt,name=conflict_term,json=conflictTerm,proto3" json:"conflict_term,omitempty"`
	// Opaque token echoed by heartbeat responses, identifying a read-index
	// round.
	Context []byte `protobuf:"bytes,16,opt,name=context,proto3" json:"context,omitempty"`
	// State machine image, present only on an install-snapshot message.
	Snapshot      *Snapshot `protobuf:"bytes,17,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Message) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Message) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Message) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *Message) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *Message) GetPrevLogIndex() uint64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *Message) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *Message) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Message) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *Message) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *Message) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Message) GetMatchIndex() uint64 {
	if x != nil {
		return x.MatchIndex
	}
	return 0
}

func (x *Message) GetConflictIndex() uint64 {
	if x != nil {
		return x.ConflictIndex
	}
	return 0
}

func (x *Message) GetConflictTerm() uint64 {
	if x != nil {
		return x.ConflictTerm
	}
	return 0
}

func (x *Message) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Message) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// DeliverRequest wraps the message being delivered.
//
// The wrapper is not ceremony: an RPC whose request type is a bare domain
// object has nowhere to put anything else later. Adding a field here — a
// sender epoch, a trace identifier, a batch of messages — is a compatible
// change, whereas changing the request type is not.
type DeliverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// ConfState is the cluster membership at a point in the log.
//
// It travels with a snapshot because it cannot be recovered any other way:
// membership lives in the log as configuration-change entries, and a snapshot
// exists precisely so those entries can be deleted.
type ConfState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authoritative voter set, or the outgoing one during a joint transition.
	Voters []uint64 `protobuf:"varint,1,rep,packed,name=voters,proto3" json:"voters,omitempty"`
	// Target voter set during a joint transition; empty otherwise.
	Incoming []uint64 `protobuf:"varint,2,rep,packed,name=incoming,proto3" json:"incoming,omitempty"`
	// Whether a transition is in progress.
	//
	// Carried rather than inferred from incoming being non-empty: a shrinking
	// transition produces a smaller incoming set and, at the limit, an empty
	// one, which would otherwise read as "no transition" and let the receiver
	// decide on a single majority while the rest of the cluster requires two.
	Joint bool `protobuf:"varint,3,opt,name=joint,proto3" json:"joint,omitempty"`
	// Network addresses, so a node restored from this configuration can reach
	// members it was never statically told about.
	Addrs         map[uint64]string `protobuf:"bytes,4,rep,name=addrs,proto3" json:"addrs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfState) Reset() {
	*x = ConfState{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfState) ProtoMessage() {}

func (x *ConfState) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfState.ProtoReflect.Descriptor instead.
func (*ConfState) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{3}
}

func (x *ConfState) GetVoters() []uint64 {
	if x != nil {
		return x.Voters
	}
	return nil
}

func (x *ConfState) GetIncoming() []uint64 {
	if x != nil {
		return x.Incoming
	}
	return nil
}

func (x *ConfState) GetJoint() bool {
	if x != nil {
		return x.Joint
	}
	return false
}

func (x *ConfState) GetAddrs() map[uint64]string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// Snapshot is a state machine image at a point in the log.
//
// A leader sends one to a follower it can no longer catch up from the log
// alone, which happens once compaction has removed the entries that follower
// still needs.
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Last log index included. A node holding this has applied everything
	// through here.
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Term of the entry at index, giving the snapshot a position the
	// log-matching rules can reason about.
	Term uint64 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	// Membership as of index.
	Conf *ConfState `protobuf:"bytes,3,opt,name=conf,proto3" json:"conf,omitempty"`
	// Serialized state machine, opaque to the consensus layer.
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{4}
}

func (x *Snapshot) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Snapshot) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Snapshot) GetConf() *ConfState {
	if x != nil {
		return x.Conf
	}
	return nil
}

func (x *Snapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeliverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResponse) Reset() {
	*x = DeliverResponse{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResponse) ProtoMessage() {}

func (x *DeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResponse.ProtoReflect.Descriptor instead.
func (*DeliverResponse) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{5}
}

// ClientRequest carries the session information that makes a retry safe.
//
// A client that does not hear back cannot tell whether its write was lost on
// the way in, applied and lost on the way out, or merely slow, so it must
// retry. The client ID and sequence number let the state machine recognize the
// retry and ignore it — without them, a retried write could be applied after a
// newer one and silently undo it.
type ClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable for the lifetime of a client connection. Zero means the request is
	// not part of a session and will not be deduplicated.
	ClientId uint64 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Strictly increasing per client. Gaps are allowed; going backwards is what
	// marks a request as a duplicate.
	Sequence      uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{6}
}

func (x *ClientRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ClientRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Value []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Whether the key exists. An empty value is a legitimate value, so this
	// cannot be inferred from the bytes.
	Found         bool `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{8}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *ClientRequest         `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{9}
}

func (x *PutRequest) GetClient() *ClientRequest {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{10}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *ClientRequest         `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRequest) GetClient() *ClientRequest {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{12}
}

// NotLeader is attached to the error returned when a request reaches a node
// that cannot serve it.
//
// It is an error detail rather than a field on every response because that is
// what it is: the request did not happen. Encoding it as a successful response
// with an "actually, no" flag would make every client remember to check, and
// the ones that forgot would silently treat a redirect as a result.
//
// The address is included so a client can redirect itself without consulting
// configuration, which matters most when membership has changed since the
// client was configured.
type NotLeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The leader this node recognizes, or zero if it knows of none — during an
	// election, for instance.
	LeaderId uint64 `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	// The leader's address, empty when unknown.
	LeaderAddress string `protobuf:"bytes,2,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotLeader) Reset() {
	*x = NotLeader{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotLeader) ProtoMessage() {}

func (x *NotLeader) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotLeader.ProtoReflect.Descriptor instead.
func (*NotLeader) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{13}
}

func (x *NotLeader) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *NotLeader) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

// Member is one node in the cluster.
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{14}
}

func (x *Member) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Member) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AddNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new member's ID. It must not already be a member.
	NodeId uint64 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Where to reach it. Required: a member the cluster cannot contact would
	// count toward every majority while never answering.
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeRequest) Reset() {
	*x = AddNodeRequest{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeRequest) ProtoMessage() {}

func (x *AddNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeRequest.ProtoReflect.Descriptor instead.
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{15}
}

func (x *AddNodeRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *AddNodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AddNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeResponse) Reset() {
	*x = AddNodeResponse{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponse) ProtoMessage() {}

func (x *AddNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponse.ProtoReflect.Descriptor instead.
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{16}
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveNodeRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type RemoveNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{18}
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{19}
}

type ListMembersResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Members []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	// Whether a membership change is currently in progress. While it is, no
	// further change can start.
	Joint         bool `protobuf:"varint,2,opt,name=joint,proto3" json:"joint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{20}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersResponse) GetJoint() bool {
	if x != nil {
		return x.Joint
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{21}
}

type StatusResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// The leader this node recognizes, or zero if it knows of none.
	LeaderId uint64 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	// The leader's address, so a client can redirect itself without consulting
	// configuration. Empty when the leader is unknown.
	LeaderAddress string    `protobuf:"bytes,3,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	Term          uint64    `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	State         NodeState `protobuf:"varint,5,opt,name=state,proto3,enum=raftkv.v1.NodeState" json:"state,omitempty"`
	CommitIndex   uint64    `protobuf:"varint,6,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	AppliedIndex  uint64    `protobuf:"varint,7,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftkv_v1_raftkv_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_raftkv_v1_raftkv_proto_rawDescGZIP(), []int{22}
}

func (x *StatusResponse) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *StatusResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *StatusResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

func (x *StatusResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *StatusResponse) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_NODE_STATE_UNSPECIFIED
}

func (x *StatusResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *StatusResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

var File_raftkv_v1_raftkv_proto protoreflect.FileDescriptor

const file_raftkv_v1_raftkv_proto_rawDesc = "" +
	"\n" +
	"\x16raftkv/v1/raftkv.proto\x12\traftkv.v1\"o\n" +
	"\x05Entry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.raftkv.v1.EntryTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xbc\x04\n" +
	"\aMessage\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.raftkv.v1.MessageTypeR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x04R\x02to\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12$\n" +
	"\x0elast_log_index\x18\x05 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x06 \x01(\x04R\vlastLogTerm\x12$\n" +
	"\x0eprev_log_index\x18\a \x01(\x04R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\b \x01(\x04R\vprevLogTerm\x12*\n" +
	"\aentries\x18\t \x03(\v2\x10.raftkv.v1.EntryR\aentries\x12!\n" +
	"\fcommit_index\x18\n" +
	" \x01(\x04R\vcommitIndex\x12\x18\n" +
	"\agranted\x18\v \x01(\bR\agranted\x12\x18\n" +
	"\asuccess\x18\f \x01(\bR\asuccess\x12\x1f\n" +
	"\vmatch_index\x18\r \x01(\x04R\n" +
	"matchIndex\x12%\n" +
	"\x0econflict_index\x18\x0e \x01(\x04R\rconflictIndex\x12#\n" +
	"\rconflict_term\x18\x0f \x01(\x04R\fconflictTerm\x12\x18\n" +
	"\acontext\x18\x10 \x01(\fR\acontext\x12/\n" +
	"\bsnapshot\x18\x11 \x01(\v2\x13.raftkv.v1.SnapshotR\bsnapshot\">\n" +
	"\x0eDeliverRequest\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.raftkv.v1.MessageR\amessage\"\xc6\x01\n" +
	"\tConfState\x12\x16\n" +
	"\x06voters\x18\x01 \x03(\x04R\x06voters\x12\x1a\n" +
	"\bincoming\x18\x02 \x03(\x04R\bincoming\x12\x14\n" +
	"\x05joint\x18\x03 \x01(\bR\x05joint\x125\n" +
	"\x05addrs\x18\x04 \x03(\v2\x1f.raftkv.v1.ConfState.AddrsEntryR\x05addrs\x1a8\n" +
	"\n" +
	"AddrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\bSnapshot\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12(\n" +
	"\x04conf\x18\x03 \x01(\v2\x14.raftkv.v1.ConfStateR\x04conf\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x11\n" +
	"\x0fDeliverResponse\"H\n" +
	"\rClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"f\n" +
	"\n" +
	"PutRequest\x120\n" +
	"\x06client\x18\x01 \x01(\v2\x18.raftkv.v1.ClientRequestR\x06client\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\r\n" +
	"\vPutResponse\"S\n" +
	"\rDeleteRequest\x120\n" +
	"\x06client\x18\x01 \x01(\v2\x18.raftkv.v1.ClientRequestR\x06client\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"O\n" +
	"\tNotLeader\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\x04R\bleaderId\x12%\n" +
	"\x0eleader_address\x18\x02 \x01(\tR\rleaderAddress\"2\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"C\n" +
	"\x0eAddNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x11\n" +
	"\x0fAddNodeResponse\",\n" +
	"\x11RemoveNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\"\x14\n" +
	"\x12RemoveNodeResponse\"\x14\n" +
	"\x12ListMembersRequest\"X\n" +
	"\x13ListMembersResponse\x12+\n" +
	"\amembers\x18\x01 \x03(\v2\x11.raftkv.v1.MemberR\amembers\x12\x14\n" +
	"\x05joint\x18\x02 \x01(\bR\x05joint\"\x0f\n" +
	"\rStatusRequest\"\xf5\x01\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x04R\bleaderId\x12%\n" +
	"\x0eleader_address\x18\x03 \x01(\tR\rleaderAddress\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12*\n" +
	"\x05state\x18\x05 \x01(\x0e2\x14.raftkv.v1.NodeStateR\x05state\x12!\n" +
	"\fcommit_index\x18\x06 \x01(\x04R\vcommitIndex\x12#\n" +
	"\rapplied_index\x18\a \x01(\x04R\fappliedIndex*\xbd\x02\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MESSAGE_TYPE_VOTE_REQUEST\x10\x01\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_VOTE_RESPONSE\x10\x02\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_APPEND_REQUEST\x10\x03\x12 \n" +
	"\x1cMESSAGE_TYPE_APPEND_RESPONSE\x10\x04\x12\x1a\n" +
	"\x16MESSAGE_TYPE_HEARTBEAT\x10\x05\x12#\n" +
	"\x1fMESSAGE_TYPE_HEARTBEAT_RESPONSE\x10\x06\x12!\n" +
	"\x1dMESSAGE_TYPE_INSTALL_SNAPSHOT\x10\a\x12*\n" +
	"&MESSAGE_TYPE_INSTALL_SNAPSHOT_RESPONSE\x10\b*p\n" +
	"\tEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ENTRY_TYPE_NORMAL\x10\x01\x12\x14\n" +
	"\x10ENTRY_TYPE_NO_OP\x10\x02\x12\x1a\n" +
	"\x16ENTRY_TYPE_CONF_CHANGE\x10\x03*q\n" +
	"\tNodeState\x12\x1a\n" +
	"\x16NODE_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13NODE_STATE_FOLLOWER\x10\x01\x12\x18\n" +
	"\x14NODE_STATE_CANDIDATE\x10\x02\x12\x15\n" +
	"\x11NODE_STATE_LEADER\x10\x032O\n" +
	"\vRaftService\x12@\n" +
	"\aDeliver\x12\x19.raftkv.v1.DeliverRequest\x1a\x1a.raftkv.v1.DeliverResponse2\xeb\x01\n" +
	"\x0eClusterService\x12@\n" +
	"\aAddNode\x12\x19.raftkv.v1.AddNodeRequest\x1a\x1a.raftkv.v1.AddNodeResponse\x12I\n" +
	"\n" +
	"RemoveNode\x12\x1c.raftkv.v1.RemoveNodeRequest\x1a\x1d.raftkv.v1.RemoveNodeResponse\x12L\n" +
	"\vListMembers\x12\x1d.raftkv.v1.ListMembersRequest\x1a\x1e.raftkv.v1.ListMembersResponse2\xf5\x01\n" +
	"\tKVService\x124\n" +
	"\x03Get\x12\x15.raftkv.v1.GetRequest\x1a\x16.raftkv.v1.GetResponse\x124\n" +
	"\x03Put\x12\x15.raftkv.v1.PutRequest\x1a\x16.raftkv.v1.PutResponse\x12=\n" +
	"\x06Delete\x12\x18.raftkv.v1.DeleteRequest\x1a\x19.raftkv.v1.DeleteResponse\x12=\n" +
	"\x06Status\x12\x18.raftkv.v1.StatusRequest\x1a\x19.raftkv.v1.StatusResponseB\xa7\x01\n" +
	"\rcom.raftkv.v1B\vRaftkvProtoP\x01ZDgithub.com/MenaceHecker/raftkv/internal/transport/raftkv/v1;raftkvv1\xa2\x02\x03RXX\xaa\x02\tRaftkv.V1\xca\x02\tRaftkv\\V1\xe2\x02\x15Raftkv\\V1\\GPBMetadata\xea\x02\n" +
	"Raftkv::V1b\x06proto3"

var (
	file_raftkv_v1_raftkv_proto_rawDescOnce sync.Once
	file_raftkv_v1_raftkv_proto_rawDescData []byte
)

func file_raftkv_v1_raftkv_proto_rawDescGZIP() []byte {
	file_raftkv_v1_raftkv_proto_rawDescOnce.Do(func() {
		file_raftkv_v1_raftkv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raftkv_v1_raftkv_proto_rawDesc), len(file_raftkv_v1_raftkv_proto_rawDesc)))
	})
	return file_raftkv_v1_raftkv_proto_rawDescData
}

var file_raftkv_v1_raftkv_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_raftkv_v1_raftkv_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_raftkv_v1_raftkv_proto_goTypes = []any{
	(MessageType)(0),            // 0: raftkv.v1.MessageType
	(EntryType)(0),              // 1: raftkv.v1.EntryType
	(NodeState)(0),              // 2: raftkv.v1.NodeState
	(*Entry)(nil),               // 3: raftkv.v1.Entry
	(*Message)(nil),             // 4: raftkv.v1.Message
	(*DeliverRequest)(nil),      // 5: raftkv.v1.DeliverRequest
	(*ConfState)(nil),           // 6: raftkv.v1.ConfState
	(*Snapshot)(nil),            // 7: raftkv.v1.Snapshot
	(*DeliverResponse)(nil),     // 8: raftkv.v1.DeliverResponse
	(*ClientRequest)(nil),       // 9: raftkv.v1.ClientRequest
	(*GetRequest)(nil),          // 10: raftkv.v1.GetRequest
	(*GetResponse)(nil),         // 11: raftkv.v1.GetResponse
	(*PutRequest)(nil),          // 12: raftkv.v1.PutRequest
	(*PutResponse)(nil),         // 13: raftkv.v1.PutResponse
	(*DeleteRequest)(nil),       // 14: raftkv.v1.DeleteRequest
	(*DeleteResponse)(nil),      // 15: raftkv.v1.DeleteResponse
	(*NotLeader)(nil),           // 16: raftkv.v1.NotLeader
	(*Member)(nil),              // 17: raftkv.v1.Member
	(*AddNodeRequest)(nil),      // 18: raftkv.v1.AddNodeRequest
	(*AddNodeResponse)(nil),     // 19: raftkv.v1.AddNodeResponse
	(*RemoveNodeRequest)(nil),   // 20: raftkv.v1.RemoveNodeRequest
	(*RemoveNodeResponse)(nil),  // 21: raftkv.v1.RemoveNodeResponse
	(*ListMembersRequest)(nil),  // 22: raftkv.v1.ListMembersRequest
	(*ListMembersResponse)(nil), // 23: raftkv.v1.ListMembersResponse
	(*StatusRequest)(nil),       // 24: raftkv.v1.StatusRequest
	(*StatusResponse)(nil),      // 25: raftkv.v1.StatusResponse
	nil,                         // 26: raftkv.v1.ConfState.AddrsEntry
}
var file_raftkv_v1_raftkv_proto_depIdxs = []int32{
	1,  // 0: raftkv.v1.Entry.type:type_name -> raftkv.v1.EntryType
	0,  // 1: raftkv.v1.Message.type:type_name -> raftkv.v1.MessageType
	3,  // 2: raftkv.v1.Message.entries:type_name -> raftkv.v1.Entry
	7,  // 3: raftkv.v1.Message.snapshot:type_name -> raftkv.v1.Snapshot
	4,  // 4: raftkv.v1.DeliverRequest.message:type_name -> raftkv.v1.Message
	26, // 5: raftkv.v1.ConfState.addrs:type_name -> raftkv.v1.ConfState.AddrsEntry
	6,  // 6: raftkv.v1.Snapshot.conf:type_name -> raftkv.v1.ConfState
	9,  // 7: raftkv.v1.PutRequest.client:type_name -> raftkv.v1.ClientRequest
	9,  // 8: raftkv.v1.DeleteRequest.client:type_name -> raftkv.v1.ClientRequest
	17, // 9: raftkv.v1.ListMembersResponse.members:type_name -> raftkv.v1.Member
	2,  // 10: raftkv.v1.StatusResponse.state:type_name -> raftkv.v1.NodeState
	5,  // 11: raftkv.v1.RaftService.Deliver:input_type -> raftkv.v1.DeliverRequest
	18, // 12: raftkv.v1.ClusterService.AddNode:input_type -> raftkv.v1.AddNodeRequest
	20, // 13: raftkv.v1.ClusterService.RemoveNode:input_type -> raftkv.v1.RemoveNodeRequest
	22, // 14: raftkv.v1.ClusterService.ListMembers:input_type -> raftkv.v1.ListMembersRequest
	10, // 15: raftkv.v1.KVService.Get:input_type -> raftkv.v1.GetRequest
	12, // 16: raftkv.v1.KVService.Put:input_type -> raftkv.v1.PutRequest
	14, // 17: raftkv.v1.KVService.Delete:input_type -> raftkv.v1.DeleteRequest
	24, // 18: raftkv.v1.KVService.Status:input_type -> raftkv.v1.StatusRequest
	8,  // 19: raftkv.v1.RaftService.Deliver:output_type -> raftkv.v1.DeliverResponse
	19, // 20: raftkv.v1.ClusterService.AddNode:output_type -> raftkv.v1.AddNodeResponse
	21, // 21: raftkv.v1.ClusterService.RemoveNode:output_type -> raftkv.v1.RemoveNodeResponse
	23, // 22: raftkv.v1.ClusterService.ListMembers:output_type -> raftkv.v1.ListMembersResponse
	11, // 23: raftkv.v1.KVService.Get:output_type -> raftkv.v1.GetResponse
	13, // 24: raftkv.v1.KVService.Put:output_type -> raftkv.v1.PutResponse
	15, // 25: raftkv.v1.KVService.Delete:output_type -> raftkv.v1.DeleteResponse
	25, // 26: raftkv.v1.KVService.Status:output_type -> raftkv.v1.StatusResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_raftkv_v1_raftkv_proto_init() }
func file_raftkv_v1_raftkv_proto_init() {
	if File_raftkv_v1_raftkv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raftkv_v1_raftkv_proto_rawDesc), len(file_raftkv_v1_raftkv_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_raftkv_v1_raftkv_proto_goTypes,
		DependencyIndexes: file_raftkv_v1_raftkv_proto_depIdxs,
		EnumInfos:         file_raftkv_v1_raftkv_proto_enumTypes,
		MessageInfos:      file_raftkv_v1_raftkv_proto_msgTypes,
	}.Build()
	File_raftkv_v1_raftkv_proto = out.File
	file_raftkv_v1_raftkv_proto_goTypes = nil
	file_raftkv_v1_raftkv_proto_depIdxs = nil
}
